// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/AnimatorState.cs
// model: AnimatorState
// codec: net
// fingerprint: sha256:946dea7480b40eb311c883b63d50dfe5b44739433bfe17780a05bbf5102edc27
// fomoxac-version: 0.2.2
// generated-at: 2026-10-01T10:52:10Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="AnimatorState"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Layout</c>: <c>u32</c></description></item>
/// <item><description><c>Speed</c>: <c>f32</c></description></item>
/// <item><description><c>Floats</c>: <c>Array&lt;f32&gt;</c></description></item>
/// <item><description><c>Ints</c>: <c>Array&lt;i32&gt;</c></description></item>
/// <item><description><c>Bools</c>: <c>Array&lt;bool&gt;</c></description></item>
/// <item><description><c>Triggers</c>: <c>Array&lt;u8&gt;</c></description></item>
/// <item><description><c>LayerWeights</c>: <c>Array&lt;f32&gt;</c></description></item>
/// <item><description><c>LayerStates</c>: <c>Array&lt;i32&gt;</c></description></item>
/// </list>
/// </remarks>
public static class AnimatorStateNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "AnimatorState.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x2CD9DD17;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x946DEA7480B40EB3;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.AnimatorState value)
    {
        writer.WriteU32(value.Layout);
        writer.WriteF32(value.Speed);
        writer.WriteArrayCount(value.Floats.Count);
        foreach (var element in value.Floats)
        {
            writer.WriteF32(element);
        }
        writer.WriteArrayCount(value.Ints.Count);
        foreach (var element in value.Ints)
        {
            writer.WriteI32(element);
        }
        writer.WriteArrayCount(value.Bools.Count);
        foreach (var element in value.Bools)
        {
            writer.WriteBool(element);
        }
        writer.WriteArrayCount(value.Triggers.Count);
        foreach (var element in value.Triggers)
        {
            writer.WriteU8(element);
        }
        writer.WriteArrayCount(value.LayerWeights.Count);
        foreach (var element in value.LayerWeights)
        {
            writer.WriteF32(element);
        }
        writer.WriteArrayCount(value.LayerStates.Count);
        foreach (var element in value.LayerStates)
        {
            writer.WriteI32(element);
        }
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.AnimatorState value)
    {
        value.Layout = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.Speed = reader.FieldAbsent() ? 0f : reader.ReadF32();
        int floatsValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var floatsValueList = ArrayField.Reuse(value.Floats, floatsValueCount);
        for (int i = 0; i < floatsValueCount; i++)
        {
            var element = reader.ReadF32();
            if (i < floatsValueList.Count)
            {
                floatsValueList[i] = element;
            }
            else
            {
                floatsValueList.Add(element);
            }
        }
        ArrayField.Trim(floatsValueList, floatsValueCount);
        value.Floats = floatsValueList;
        int intsValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var intsValueList = ArrayField.Reuse(value.Ints, intsValueCount);
        for (int i = 0; i < intsValueCount; i++)
        {
            var element = reader.ReadI32();
            if (i < intsValueList.Count)
            {
                intsValueList[i] = element;
            }
            else
            {
                intsValueList.Add(element);
            }
        }
        ArrayField.Trim(intsValueList, intsValueCount);
        value.Ints = intsValueList;
        int boolsValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var boolsValueList = ArrayField.Reuse(value.Bools, boolsValueCount);
        for (int i = 0; i < boolsValueCount; i++)
        {
            var element = reader.ReadBool();
            if (i < boolsValueList.Count)
            {
                boolsValueList[i] = element;
            }
            else
            {
                boolsValueList.Add(element);
            }
        }
        ArrayField.Trim(boolsValueList, boolsValueCount);
        value.Bools = boolsValueList;
        int triggersValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var triggersValueList = ArrayField.Reuse(value.Triggers, triggersValueCount);
        for (int i = 0; i < triggersValueCount; i++)
        {
            var element = reader.ReadU8();
            if (i < triggersValueList.Count)
            {
                triggersValueList[i] = element;
            }
            else
            {
                triggersValueList.Add(element);
            }
        }
        ArrayField.Trim(triggersValueList, triggersValueCount);
        value.Triggers = triggersValueList;
        int layerWeightsValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var layerWeightsValueList = ArrayField.Reuse(value.LayerWeights, layerWeightsValueCount);
        for (int i = 0; i < layerWeightsValueCount; i++)
        {
            var element = reader.ReadF32();
            if (i < layerWeightsValueList.Count)
            {
                layerWeightsValueList[i] = element;
            }
            else
            {
                layerWeightsValueList.Add(element);
            }
        }
        ArrayField.Trim(layerWeightsValueList, layerWeightsValueCount);
        value.LayerWeights = layerWeightsValueList;
        int layerStatesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var layerStatesValueList = ArrayField.Reuse(value.LayerStates, layerStatesValueCount);
        for (int i = 0; i < layerStatesValueCount; i++)
        {
            var element = reader.ReadI32();
            if (i < layerStatesValueList.Count)
            {
                layerStatesValueList[i] = element;
            }
            else
            {
                layerStatesValueList.Add(element);
            }
        }
        ArrayField.Trim(layerStatesValueList, layerStatesValueCount);
        value.LayerStates = layerStatesValueList;
    }
}

}
