// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/MessageBundle.cs
// model: BundleEntry
// codec: net
// fingerprint: sha256:9adca46177a3570704e3f058abe3ca6e851391cbc460bb7ffa402ec69b68ba34
// fomoxac-version: 0.2.2
// generated-at: 2026-09-25T07:23:08Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="BundleEntry"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>MessageId</c>: <c>u32</c></description></item>
/// <item><description><c>Data</c>: <c>bytes</c></description></item>
/// </list>
/// </remarks>
public static class BundleEntryNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "BundleEntry.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xEB3D601A;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x9ADCA46177A35707;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.BundleEntry value)
    {
        writer.WriteU32(value.MessageId);
        writer.WriteBytes(value.Data);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.BundleEntry value)
    {
        value.MessageId = reader.FieldAbsent() ? 0 : reader.ReadU32();
        var dataValue = value.Data;
        if (reader.FieldAbsent())
        {
            dataValue = System.Array.Empty<byte>();
        }
        else
        {
            reader.ReadBytes(ref dataValue);
        }
        value.Data = dataValue;
    }
}

}
