// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// fingerprint: sha256:ba464f0d00504543dd6c721110a0a9327f5e6cbba2ebed5c20d12f440c269d65
// fomoxac-version: 0.2.2
// generated-at: 2026-10-07T06:14:32Z
//
// Every fingerprint this schema publishes, and the handshake that compares
// them. Generated - never edit, and never hand-maintain a copy of these
// values anywhere else.

namespace BundleFixture
{

/// <summary>One message: its id, its name, and the fingerprint of its wire
/// contract.</summary>
public readonly struct FomoxaMessage
{
    /// <summary>Stable across schema changes; derived from the name alone.</summary>
    public readonly uint Id;
    /// <summary><c>Model.codec</c>.</summary>
    public readonly string Name;
    /// <summary>Changes whenever the message's fields do.</summary>
    public readonly ulong Fingerprint;
    /// <summary>One entry per field: entry <c>k-1</c> covers the first <c>k</c> fields.
    /// The last entry is <see cref="Fingerprint"/>. Stays local; only its length and its
    /// last entry ever go on the wire.</summary>
    public readonly ulong[] Prefixes;

    public FomoxaMessage(uint id, string name, ulong fingerprint, ulong[] prefixes)
    {
        Id = id;
        Name = name;
        Fingerprint = fingerprint;
        Prefixes = prefixes;
    }
}

/// <summary>One entry of a peer's (id, field count, fingerprint) table - what
/// <see cref="Handshake.FomoxaMessages"/> is on its side.</summary>
public readonly struct FomoxaPeerMessage
{
    public readonly uint Id;
    public readonly uint FieldCount;
    public readonly ulong Fingerprint;

    public FomoxaPeerMessage(uint id, uint fieldCount, ulong fingerprint)
    {
        Id = id;
        FieldCount = fieldCount;
        Fingerprint = fingerprint;
    }
}

/// <summary>What a peer's fingerprints mean for this one.</summary>
public enum FomoxaHandshake
{
    /// <summary>The same schema, exactly.</summary>
    Current,
    /// <summary>A different schema, but every message both ends know agrees on the
    /// fields both ends carry. Safe to proceed.</summary>
    Outdated,
    /// <summary>Both ends put different fields at an index both of them carry. There is
    /// nothing to negotiate: disconnect.</summary>
    Reject,
    /// <summary>Not decidable from the peer's table alone - at least one message needs
    /// the extra exchange described on <see cref="FomoxaMessageCheck.NeedPrefix"/>.</summary>
    NeedMore,
}

/// <summary>What one of the peer's messages means for this schema's message of the same
/// id.</summary>
public enum FomoxaMessageCheck
{
    /// <summary>Either this schema does not declare the message at all, or the fields
    /// both ends carry agree. Nothing to do.</summary>
    Match,
    /// <summary>Both ends put different fields at an index both of them carry.</summary>
    Reject,
    /// <summary>Undecidable from what the peer sent: the peer has more fields than this
    /// schema, so the answer lives at an index only the peer can produce. Ask it for its
    /// prefix fingerprint at the reported field count, then compare the reply against
    /// <c>FomoxaPrefix</c> for the same id.</summary>
    NeedPrefix,
}

/// <summary>One message: its id, its name, and the fingerprint of its wire
/// contract.</summary>
public static class Handshake
{
    /// <summary>The fingerprint of the whole schema: every message, by name, with its own
    /// fingerprint, hashed together. Two peers that agree on this agree on
    /// everything.</summary>
    public const ulong FomoxaSchemaFingerprint = 0xBA464F0D00504543;

    /// <summary><c>AnimatorState</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong AnimatorStateFingerprint = 0x994EAA2D09AA7914;

    /// <summary><c>AnimatorState.net</c> - the wire contract <c>AnimatorStateNetCodec</c> encodes and decodes.</summary>
    public const uint AnimatorStateNetMessageId = 0x2CD9DD17;
    public const ulong AnimatorStateNetFingerprint = 0x946DEA7480B40EB3;
    /// <summary>One fingerprint per prefix of <c>AnimatorState.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="AnimatorStateNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] AnimatorStateNetPrefixes = new ulong[]
    {
        0x9826703D9C9BBC16,
        0x20EF0FBAC83667D5,
        0xC437AC7CCBF71331,
        0xEE87CE024C9BE9C2,
        0xE88740426C6688E3,
        0x8C6D5EFBA2D77D6A,
        0xFD8AA11EAC526FBD,
        0x946DEA7480B40EB3,
    };

    /// <summary><c>BundleEntry</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong BundleEntryFingerprint = 0xCF6A3D54E00296E4;

    /// <summary><c>BundleEntry.net</c> - the wire contract <c>BundleEntryNetCodec</c> encodes and decodes.</summary>
    public const uint BundleEntryNetMessageId = 0xEB3D601A;
    public const ulong BundleEntryNetFingerprint = 0x9ADCA46177A35707;
    /// <summary>One fingerprint per prefix of <c>BundleEntry.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="BundleEntryNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] BundleEntryNetPrefixes = new ulong[]
    {
        0xF39BDC7517FB08A1,
        0x9ADCA46177A35707,
    };

    /// <summary><c>InputFrames</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong InputFramesFingerprint = 0xB0C40EC29F5FC7FA;

    /// <summary><c>InputFrames.net</c> - the wire contract <c>InputFramesNetCodec</c> encodes and decodes.</summary>
    public const uint InputFramesNetMessageId = 0x5D0051BA;
    public const ulong InputFramesNetFingerprint = 0x0FF27ABFB43D4C62;
    /// <summary>One fingerprint per prefix of <c>InputFrames.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="InputFramesNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] InputFramesNetPrefixes = new ulong[]
    {
        0x9191C5FE7594AA4D,
        0x0FF27ABFB43D4C62,
    };

    /// <summary><c>LocalPeer</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong LocalPeerFingerprint = 0x6B3D297716473A21;

    /// <summary><c>LocalPeer.net</c> - the wire contract <c>LocalPeerNetCodec</c> encodes and decodes.</summary>
    public const uint LocalPeerNetMessageId = 0x90528974;
    public const ulong LocalPeerNetFingerprint = 0xA5D4734EF76F4DFC;
    /// <summary>One fingerprint per prefix of <c>LocalPeer.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="LocalPeerNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] LocalPeerNetPrefixes = new ulong[]
    {
        0x2A67334548101C9F,
        0xB8E85B1BCB88D1AF,
        0xA5D4734EF76F4DFC,
    };

    /// <summary><c>MessageBundle</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong MessageBundleFingerprint = 0x22FF508D0530E79A;

    /// <summary><c>MessageBundle.net</c> - the wire contract <c>MessageBundleNetCodec</c> encodes and decodes.</summary>
    public const uint MessageBundleNetMessageId = 0xA3EC30B8;
    public const ulong MessageBundleNetFingerprint = 0x50CB0322CC54BE41;
    /// <summary>One fingerprint per prefix of <c>MessageBundle.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="MessageBundleNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] MessageBundleNetPrefixes = new ulong[]
    {
        0x50CB0322CC54BE41,
    };

    /// <summary><c>ObjectDespawn</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong ObjectDespawnFingerprint = 0x78802DEACA99E5C6;

    /// <summary><c>ObjectDespawn.net</c> - the wire contract <c>ObjectDespawnNetCodec</c> encodes and decodes.</summary>
    public const uint ObjectDespawnNetMessageId = 0x517BFA7D;
    public const ulong ObjectDespawnNetFingerprint = 0xDDA307DE04EF4296;
    /// <summary>One fingerprint per prefix of <c>ObjectDespawn.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="ObjectDespawnNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] ObjectDespawnNetPrefixes = new ulong[]
    {
        0xDDA307DE04EF4296,
    };

    /// <summary><c>ObjectOwnerChange</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong ObjectOwnerChangeFingerprint = 0x9436BFA5D7C31B1C;

    /// <summary><c>ObjectOwnerChange.net</c> - the wire contract <c>ObjectOwnerChangeNetCodec</c> encodes and decodes.</summary>
    public const uint ObjectOwnerChangeNetMessageId = 0x22F1F1F7;
    public const ulong ObjectOwnerChangeNetFingerprint = 0x6969477015076F20;
    /// <summary>One fingerprint per prefix of <c>ObjectOwnerChange.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="ObjectOwnerChangeNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] ObjectOwnerChangeNetPrefixes = new ulong[]
    {
        0xE30690E3CAA86413,
        0x6969477015076F20,
    };

    /// <summary><c>ObjectSceneSpawn</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong ObjectSceneSpawnFingerprint = 0x3062D599D0A77571;

    /// <summary><c>ObjectSceneSpawn.net</c> - the wire contract <c>ObjectSceneSpawnNetCodec</c> encodes and decodes.</summary>
    public const uint ObjectSceneSpawnNetMessageId = 0x756E5838;
    public const ulong ObjectSceneSpawnNetFingerprint = 0xA93D679DB7A042D3;
    /// <summary>One fingerprint per prefix of <c>ObjectSceneSpawn.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="ObjectSceneSpawnNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] ObjectSceneSpawnNetPrefixes = new ulong[]
    {
        0x443E996D2B6904AB,
        0x06F0A33FF3441633,
        0x77DFDB11FD5744B3,
        0x52E0D8E4B54AB16A,
        0x54B46ACD7A6A6187,
        0xD59807CBCE7BFEB3,
        0xA93D679DB7A042D3,
    };

    /// <summary><c>ObjectSpawn</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong ObjectSpawnFingerprint = 0x36995A036740FA9F;

    /// <summary><c>ObjectSpawn.net</c> - the wire contract <c>ObjectSpawnNetCodec</c> encodes and decodes.</summary>
    public const uint ObjectSpawnNetMessageId = 0x56998979;
    public const ulong ObjectSpawnNetFingerprint = 0x89252CEB40D1F477;
    /// <summary>One fingerprint per prefix of <c>ObjectSpawn.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="ObjectSpawnNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] ObjectSpawnNetPrefixes = new ulong[]
    {
        0x84CD3E16AFD4C6CA,
        0x361B548B5AE13383,
        0x3C4652A3BF8FAA78,
        0x7DB7168D4627EEB0,
        0x40688222090004F8,
        0xDF8DB46A701BA821,
        0x8E942F7F27ED986A,
        0x89252CEB40D1F477,
    };

    /// <summary><c>PeerLeave</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong PeerLeaveFingerprint = 0xB00CDD65E7121331;

    /// <summary><c>PeerLeave.net</c> - the wire contract <c>PeerLeaveNetCodec</c> encodes and decodes.</summary>
    public const uint PeerLeaveNetMessageId = 0xC524CDA7;
    public const ulong PeerLeaveNetFingerprint = 0x2AC3087C85A89966;
    /// <summary>One fingerprint per prefix of <c>PeerLeave.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="PeerLeaveNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] PeerLeaveNetPrefixes = new ulong[]
    {
    };

    /// <summary><c>ReconcileState</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong ReconcileStateFingerprint = 0x0D37AA9D4229F628;

    /// <summary><c>ReconcileState.net</c> - the wire contract <c>ReconcileStateNetCodec</c> encodes and decodes.</summary>
    public const uint ReconcileStateNetMessageId = 0x3DC88FCE;
    public const ulong ReconcileStateNetFingerprint = 0x3D41C0DB5E4F6CC2;
    /// <summary>One fingerprint per prefix of <c>ReconcileState.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="ReconcileStateNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] ReconcileStateNetPrefixes = new ulong[]
    {
        0x9609D09FE623613E,
        0x3D41C0DB5E4F6CC2,
    };

    /// <summary><c>ReliableAck</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong ReliableAckFingerprint = 0x1545ED016649EA60;

    /// <summary><c>ReliableAck.net</c> - the wire contract <c>ReliableAckNetCodec</c> encodes and decodes.</summary>
    public const uint ReliableAckNetMessageId = 0x5FE1C726;
    public const ulong ReliableAckNetFingerprint = 0x2919CB926D7C0B4B;
    /// <summary>One fingerprint per prefix of <c>ReliableAck.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="ReliableAckNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] ReliableAckNetPrefixes = new ulong[]
    {
        0xC99FEC249E9B8675,
        0x2919CB926D7C0B4B,
    };

    /// <summary><c>SceneFile</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFileFingerprint = 0xDA6AFA724ADBF3AC;

    /// <summary><c>SceneFile.net</c> - the wire contract <c>SceneFileNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFileNetMessageId = 0xB4F8C111;
    public const ulong SceneFileNetFingerprint = 0xD9C44C7E4A9B807F;
    /// <summary>One fingerprint per prefix of <c>SceneFile.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFileNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFileNetPrefixes = new ulong[]
    {
        0x5937D43BF2EA0E95,
        0x9A9B0DA718C9FD81,
        0x69E2DDA8E4E832E9,
        0x227128739D2F727B,
        0x229264D51A4A4E69,
        0xD9C44C7E4A9B807F,
    };

    /// <summary><c>SceneFileBody</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFileBodyFingerprint = 0xF98C4C5D53C2AFB1;

    /// <summary><c>SceneFileBody.net</c> - the wire contract <c>SceneFileBodyNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFileBodyNetMessageId = 0x8E2999CF;
    public const ulong SceneFileBodyNetFingerprint = 0x89DA94A05C0DE9B0;
    /// <summary>One fingerprint per prefix of <c>SceneFileBody.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFileBodyNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFileBodyNetPrefixes = new ulong[]
    {
        0x17F6EAC366147EB9,
        0x1536795AE9043869,
        0x89DA94A05C0DE9B0,
    };

    /// <summary><c>SceneFileBody2D</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFileBody2DFingerprint = 0xFB4BDEF0E09A1DA0;

    /// <summary><c>SceneFileBody2D.net</c> - the wire contract <c>SceneFileBody2DNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFileBody2DNetMessageId = 0x6B520AFA;
    public const ulong SceneFileBody2DNetFingerprint = 0x8EEE3C45AE3E2344;
    /// <summary>One fingerprint per prefix of <c>SceneFileBody2D.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFileBody2DNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFileBody2DNetPrefixes = new ulong[]
    {
        0x5EAB39396A0D2044,
        0x0000DE96DDAC112A,
        0xCCD27C5E2E56530B,
        0x8EEE3C45AE3E2344,
    };

    /// <summary><c>SceneFileCollider</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFileColliderFingerprint = 0x835C08F78B4AA907;

    /// <summary><c>SceneFileCollider.net</c> - the wire contract <c>SceneFileColliderNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFileColliderNetMessageId = 0x5E871785;
    public const ulong SceneFileColliderNetFingerprint = 0x238CB95EF64C099A;
    /// <summary>One fingerprint per prefix of <c>SceneFileCollider.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFileColliderNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFileColliderNetPrefixes = new ulong[]
    {
        0x90DC185ED0FD26A4,
        0x498A222D04B730F0,
        0x0F0D03439262DA13,
        0x1822D7882D713F76,
        0xF31F6E8D9367437F,
        0x23FD8EC25E8FA6D9,
        0x86DF906EC55AFE11,
        0xA2451AB8F9E7537E,
        0x5A869A68D40809F1,
        0xC28D5394FF25A9D4,
        0x7071CD49B1EE9B3F,
        0x963BF51377328F3A,
        0x7BA553B0A0DA041C,
        0xBB3A05C6E8E3F733,
        0x27C374312E489E5C,
        0x65B7EA76485F7BF3,
        0xB98C64E0FBBAC468,
        0x238CB95EF64C099A,
    };

    /// <summary><c>SceneFileCollider2D</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFileCollider2DFingerprint = 0x733658A8DDAF2F74;

    /// <summary><c>SceneFileCollider2D.net</c> - the wire contract <c>SceneFileCollider2DNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFileCollider2DNetMessageId = 0x5E210AD5;
    public const ulong SceneFileCollider2DNetFingerprint = 0x95E8D55E703FD8B4;
    /// <summary>One fingerprint per prefix of <c>SceneFileCollider2D.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFileCollider2DNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFileCollider2DNetPrefixes = new ulong[]
    {
        0x35651CD08B858BFF,
        0xC38207761D2356A9,
        0xED8D363A3EF1BF3F,
        0x691DFD56CF4B80DA,
        0x05BA56B644E9E21B,
        0x35F9D67F64A9CE4A,
        0x1B8C3EEF7C5B646F,
        0x3381C27EF38B9018,
        0x0EC7BDABBB88FDBE,
        0xCDFE8FA97FF32173,
        0x331083BD2D4B4C67,
        0x95E8D55E703FD8B4,
    };

    /// <summary><c>SceneFileMaterial</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFileMaterialFingerprint = 0x85826FBD5F0944D0;

    /// <summary><c>SceneFileMaterial.net</c> - the wire contract <c>SceneFileMaterialNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFileMaterialNetMessageId = 0xDF07827C;
    public const ulong SceneFileMaterialNetFingerprint = 0x18E04A1F8BC79A16;
    /// <summary>One fingerprint per prefix of <c>SceneFileMaterial.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFileMaterialNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFileMaterialNetPrefixes = new ulong[]
    {
        0xE34F77693E709B73,
        0xC1BEFF9FDF1B0C75,
        0xF01DC45611E91CFE,
        0x18E04A1F8BC79A16,
    };

    /// <summary><c>SceneFileObject</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFileObjectFingerprint = 0x8108C0CFC3EE3CCB;

    /// <summary><c>SceneFileObject.net</c> - the wire contract <c>SceneFileObjectNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFileObjectNetMessageId = 0xA8BBC53D;
    public const ulong SceneFileObjectNetFingerprint = 0x2F95D86D6B2B7E7F;
    /// <summary>One fingerprint per prefix of <c>SceneFileObject.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFileObjectNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFileObjectNetPrefixes = new ulong[]
    {
        0x114C65A161787C67,
        0xE4A44BA42CACF205,
        0x222D7A923C4159E6,
        0x59C69BA0955BE7CD,
        0x2AD28D95A4031422,
        0x2F95D86D6B2B7E7F,
    };

    /// <summary><c>SceneFilePose</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneFilePoseFingerprint = 0xE4FFC266767B2645;

    /// <summary><c>SceneFilePose.net</c> - the wire contract <c>SceneFilePoseNetCodec</c> encodes and decodes.</summary>
    public const uint SceneFilePoseNetMessageId = 0xA1C331C5;
    public const ulong SceneFilePoseNetFingerprint = 0x402F32A52F8FC3BE;
    /// <summary>One fingerprint per prefix of <c>SceneFilePose.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneFilePoseNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneFilePoseNetPrefixes = new ulong[]
    {
        0x93EC6F2B8722348B,
        0xBAD90437C20C99AF,
        0xF42D782306B83493,
        0x489EE1D38172F89B,
        0x2AB86457AEA42B82,
        0x0166D3B2DCB68A72,
        0xC80D7C5986EB7F05,
        0x9ED9D0C81B8A337D,
        0x32B530EEC0F4AC97,
        0x402F32A52F8FC3BE,
    };

    /// <summary><c>SceneLoad</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneLoadFingerprint = 0xBC66107BA8F8C649;

    /// <summary><c>SceneLoad.net</c> - the wire contract <c>SceneLoadNetCodec</c> encodes and decodes.</summary>
    public const uint SceneLoadNetMessageId = 0x4D3D43BA;
    public const ulong SceneLoadNetFingerprint = 0x0061DC248BD029C7;
    /// <summary>One fingerprint per prefix of <c>SceneLoad.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneLoadNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneLoadNetPrefixes = new ulong[]
    {
        0xD1BD117560DAA150,
        0x0061DC248BD029C7,
    };

    /// <summary><c>SceneLoaded</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneLoadedFingerprint = 0x29E34F1964791D66;

    /// <summary><c>SceneLoaded.net</c> - the wire contract <c>SceneLoadedNetCodec</c> encodes and decodes.</summary>
    public const uint SceneLoadedNetMessageId = 0xDD70ED92;
    public const ulong SceneLoadedNetFingerprint = 0xD4BA7FC5758AA400;
    /// <summary>One fingerprint per prefix of <c>SceneLoaded.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneLoadedNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneLoadedNetPrefixes = new ulong[]
    {
        0xD4BA7FC5758AA400,
    };

    /// <summary><c>SceneUnload</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong SceneUnloadFingerprint = 0x13A970DC64104084;

    /// <summary><c>SceneUnload.net</c> - the wire contract <c>SceneUnloadNetCodec</c> encodes and decodes.</summary>
    public const uint SceneUnloadNetMessageId = 0x5D92EA46;
    public const ulong SceneUnloadNetFingerprint = 0x4E7375E4E9DC5E68;
    /// <summary>One fingerprint per prefix of <c>SceneUnload.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="SceneUnloadNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] SceneUnloadNetPrefixes = new ulong[]
    {
        0x4E7375E4E9DC5E68,
    };

    /// <summary><c>StateDelta</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong StateDeltaFingerprint = 0x6892021E7EB6F979;

    /// <summary><c>StateDelta.net</c> - the wire contract <c>StateDeltaNetCodec</c> encodes and decodes.</summary>
    public const uint StateDeltaNetMessageId = 0xEE8A1FC0;
    public const ulong StateDeltaNetFingerprint = 0xC709753CE0CAEDB5;
    /// <summary>One fingerprint per prefix of <c>StateDelta.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="StateDeltaNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] StateDeltaNetPrefixes = new ulong[]
    {
        0xC709753CE0CAEDB5,
    };

    /// <summary><c>StateResync</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong StateResyncFingerprint = 0x6F90727C06A0F601;

    /// <summary><c>StateResync.net</c> - the wire contract <c>StateResyncNetCodec</c> encodes and decodes.</summary>
    public const uint StateResyncNetMessageId = 0x1B21B0D1;
    public const ulong StateResyncNetFingerprint = 0x036DB9745FFC78FA;
    /// <summary>One fingerprint per prefix of <c>StateResync.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="StateResyncNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] StateResyncNetPrefixes = new ulong[]
    {
    };

    /// <summary><c>TickPing</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong TickPingFingerprint = 0x1DCFABFB297F7335;

    /// <summary><c>TickPing.net</c> - the wire contract <c>TickPingNetCodec</c> encodes and decodes.</summary>
    public const uint TickPingNetMessageId = 0xC19D0BA9;
    public const ulong TickPingNetFingerprint = 0x1D6E28CF0D4B9AB3;
    /// <summary>One fingerprint per prefix of <c>TickPing.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="TickPingNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] TickPingNetPrefixes = new ulong[]
    {
        0xBCFA438CB4947C10,
        0x1D6E28CF0D4B9AB3,
    };

    /// <summary><c>TickPong</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong TickPongFingerprint = 0xB6689E9A0CFBE40B;

    /// <summary><c>TickPong.net</c> - the wire contract <c>TickPongNetCodec</c> encodes and decodes.</summary>
    public const uint TickPongNetMessageId = 0xC9F14452;
    public const ulong TickPongNetFingerprint = 0x89FEF9F4FB791B95;
    /// <summary>One fingerprint per prefix of <c>TickPong.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="TickPongNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] TickPongNetPrefixes = new ulong[]
    {
        0x09FA50DD1D3595E2,
        0x2E14998F2A5F5ACE,
        0x89FEF9F4FB791B95,
    };

    /// <summary><c>TransformSettle</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong TransformSettleFingerprint = 0x2BA7C587C19552A8;

    /// <summary><c>TransformSettle.net</c> - the wire contract <c>TransformSettleNetCodec</c> encodes and decodes.</summary>
    public const uint TransformSettleNetMessageId = 0x62ADC0F1;
    public const ulong TransformSettleNetFingerprint = 0x671368CB7BBE68D8;
    /// <summary>One fingerprint per prefix of <c>TransformSettle.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="TransformSettleNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] TransformSettleNetPrefixes = new ulong[]
    {
        0xBFEC5145E1A8978B,
        0xF58E0F1B0A192E6F,
        0x79FDC1D3329C245C,
        0x671368CB7BBE68D8,
    };

    /// <summary><c>TransformUpdate</c>, as declared - every annotated field, whatever codec it joined.</summary>
    public const ulong TransformUpdateFingerprint = 0x6773ED05919F8CF4;

    /// <summary><c>TransformUpdate.net</c> - the wire contract <c>TransformUpdateNetCodec</c> encodes and decodes.</summary>
    public const uint TransformUpdateNetMessageId = 0x7183722F;
    public const ulong TransformUpdateNetFingerprint = 0x62CFA8A4088D2D77;
    /// <summary>One fingerprint per prefix of <c>TransformUpdate.net</c>: entry <c>k-1</c>
    /// covers its first <c>k</c> fields. The last entry is
    /// <see cref="TransformUpdateNetFingerprint"/>. Never sent whole - a peer
    /// sends its field count and its last entry, and the two sides
    /// compare at <c>min</c> of the two counts (RFC-0002 9.1).</summary>
    public static readonly ulong[] TransformUpdateNetPrefixes = new ulong[]
    {
        0xD3C3D8D2FF7E95AE,
        0xD26A5591289D89C2,
        0xED867441BCD8E333,
        0x62CFA8A4088D2D77,
    };

    /// <summary>Every message this schema declares, sorted by id.</summary>
    public static readonly FomoxaMessage[] FomoxaMessages = new FomoxaMessage[]
    {
        new FomoxaMessage(StateResyncNetMessageId, "StateResync.net", StateResyncNetFingerprint, StateResyncNetPrefixes),
        new FomoxaMessage(ObjectOwnerChangeNetMessageId, "ObjectOwnerChange.net", ObjectOwnerChangeNetFingerprint, ObjectOwnerChangeNetPrefixes),
        new FomoxaMessage(AnimatorStateNetMessageId, "AnimatorState.net", AnimatorStateNetFingerprint, AnimatorStateNetPrefixes),
        new FomoxaMessage(ReconcileStateNetMessageId, "ReconcileState.net", ReconcileStateNetFingerprint, ReconcileStateNetPrefixes),
        new FomoxaMessage(SceneLoadNetMessageId, "SceneLoad.net", SceneLoadNetFingerprint, SceneLoadNetPrefixes),
        new FomoxaMessage(ObjectDespawnNetMessageId, "ObjectDespawn.net", ObjectDespawnNetFingerprint, ObjectDespawnNetPrefixes),
        new FomoxaMessage(ObjectSpawnNetMessageId, "ObjectSpawn.net", ObjectSpawnNetFingerprint, ObjectSpawnNetPrefixes),
        new FomoxaMessage(InputFramesNetMessageId, "InputFrames.net", InputFramesNetFingerprint, InputFramesNetPrefixes),
        new FomoxaMessage(SceneUnloadNetMessageId, "SceneUnload.net", SceneUnloadNetFingerprint, SceneUnloadNetPrefixes),
        new FomoxaMessage(SceneFileCollider2DNetMessageId, "SceneFileCollider2D.net", SceneFileCollider2DNetFingerprint, SceneFileCollider2DNetPrefixes),
        new FomoxaMessage(SceneFileColliderNetMessageId, "SceneFileCollider.net", SceneFileColliderNetFingerprint, SceneFileColliderNetPrefixes),
        new FomoxaMessage(ReliableAckNetMessageId, "ReliableAck.net", ReliableAckNetFingerprint, ReliableAckNetPrefixes),
        new FomoxaMessage(TransformSettleNetMessageId, "TransformSettle.net", TransformSettleNetFingerprint, TransformSettleNetPrefixes),
        new FomoxaMessage(SceneFileBody2DNetMessageId, "SceneFileBody2D.net", SceneFileBody2DNetFingerprint, SceneFileBody2DNetPrefixes),
        new FomoxaMessage(TransformUpdateNetMessageId, "TransformUpdate.net", TransformUpdateNetFingerprint, TransformUpdateNetPrefixes),
        new FomoxaMessage(ObjectSceneSpawnNetMessageId, "ObjectSceneSpawn.net", ObjectSceneSpawnNetFingerprint, ObjectSceneSpawnNetPrefixes),
        new FomoxaMessage(SceneFileBodyNetMessageId, "SceneFileBody.net", SceneFileBodyNetFingerprint, SceneFileBodyNetPrefixes),
        new FomoxaMessage(LocalPeerNetMessageId, "LocalPeer.net", LocalPeerNetFingerprint, LocalPeerNetPrefixes),
        new FomoxaMessage(SceneFilePoseNetMessageId, "SceneFilePose.net", SceneFilePoseNetFingerprint, SceneFilePoseNetPrefixes),
        new FomoxaMessage(MessageBundleNetMessageId, "MessageBundle.net", MessageBundleNetFingerprint, MessageBundleNetPrefixes),
        new FomoxaMessage(SceneFileObjectNetMessageId, "SceneFileObject.net", SceneFileObjectNetFingerprint, SceneFileObjectNetPrefixes),
        new FomoxaMessage(SceneFileNetMessageId, "SceneFile.net", SceneFileNetFingerprint, SceneFileNetPrefixes),
        new FomoxaMessage(TickPingNetMessageId, "TickPing.net", TickPingNetFingerprint, TickPingNetPrefixes),
        new FomoxaMessage(PeerLeaveNetMessageId, "PeerLeave.net", PeerLeaveNetFingerprint, PeerLeaveNetPrefixes),
        new FomoxaMessage(TickPongNetMessageId, "TickPong.net", TickPongNetFingerprint, TickPongNetPrefixes),
        new FomoxaMessage(SceneLoadedNetMessageId, "SceneLoaded.net", SceneLoadedNetFingerprint, SceneLoadedNetPrefixes),
        new FomoxaMessage(SceneFileMaterialNetMessageId, "SceneFileMaterial.net", SceneFileMaterialNetFingerprint, SceneFileMaterialNetPrefixes),
        new FomoxaMessage(BundleEntryNetMessageId, "BundleEntry.net", BundleEntryNetFingerprint, BundleEntryNetPrefixes),
        new FomoxaMessage(StateDeltaNetMessageId, "StateDelta.net", StateDeltaNetFingerprint, StateDeltaNetPrefixes),
    };

    /// <summary>The message with this id, if this schema declares it.</summary>
    public static FomoxaMessage? FomoxaMessageById(uint id)
    {
        int low = 0;
        int high = FomoxaMessages.Length;
        while (low < high)
        {
            int middle = (low + high) / 2;
            if (FomoxaMessages[middle].Id < id)
            {
                low = middle + 1;
            }
            else
            {
                high = middle;
            }
        }
        if (low < FomoxaMessages.Length && FomoxaMessages[low].Id == id)
        {
            return FomoxaMessages[low];
        }
        return null;
    }

    /// <summary>This schema's fingerprint for the first <paramref name="fieldCount"/>
    /// fields of a message, or <c>null</c> if it does not declare that message or does
    /// not have that many fields. <paramref name="fieldCount"/> counts from 1; 0 is the
    /// empty prefix and has no fingerprint because it always matches.</summary>
    public static ulong? FomoxaPrefix(uint id, uint fieldCount)
    {
        var message = FomoxaMessageById(id);
        if (!message.HasValue || fieldCount == 0 || fieldCount > message.Value.Prefixes.Length)
        {
            return null;
        }
        return message.Value.Prefixes[fieldCount - 1];
    }

    /// <summary>Compares one of the peer's messages against this schema's.</summary>
    /// <remarks>This is RFC-0002 9.1's prefix test: the two are compatible when the
    /// shorter field list is an exact prefix of the longer one, so the comparison happens
    /// at the smaller of the two field counts. <paramref name="askFor"/> is the field
    /// count to ask the peer about, and is only meaningful for
    /// <see cref="FomoxaMessageCheck.NeedPrefix"/>.</remarks>
    public static FomoxaMessageCheck FomoxaCheckMessage(
        uint id,
        uint peerFieldCount,
        ulong peerFingerprint,
        out uint askFor)
    {
        askFor = 0;
        var message = FomoxaMessageById(id);
        if (!message.HasValue)
        {
            // Not a message this schema declares, so it is never exchanged.
            return FomoxaMessageCheck.Match;
        }
        var known = message.Value;
        uint localFieldCount = (uint)known.Prefixes.Length;

        if (peerFingerprint == known.Fingerprint)
        {
            return FomoxaMessageCheck.Match;
        }
        if (peerFieldCount == 0 || localFieldCount == 0)
        {
            // The empty field list is a prefix of everything.
            return FomoxaMessageCheck.Match;
        }
        if (peerFieldCount == localFieldCount)
        {
            // Same length, different content - a prefix of equal length would
            // have to be equality, and it is not.
            return FomoxaMessageCheck.Reject;
        }
        if (peerFieldCount < localFieldCount)
        {
            // The peer's own fingerprint already is the value at the shared index.
            return known.Prefixes[peerFieldCount - 1] == peerFingerprint
                ? FomoxaMessageCheck.Match
                : FomoxaMessageCheck.Reject;
        }
        askFor = localFieldCount;
        return FomoxaMessageCheck.NeedPrefix;
    }

    /// <summary>Compares a peer's whole message table against this schema's.</summary>
    /// <remarks>A <see cref="FomoxaHandshake.NeedMore"/> result means at least one
    /// message needs the extra round; walk the table with
    /// <see cref="FomoxaCheckMessage"/> to find which ones.</remarks>
    public static FomoxaHandshake FomoxaHandshakeCompare(
        ulong peerSchemaFingerprint,
        System.Collections.Generic.IEnumerable<FomoxaPeerMessage> peerMessages)
    {
        if (peerSchemaFingerprint == FomoxaSchemaFingerprint)
        {
            return FomoxaHandshake.Current;
        }

        bool needMore = false;
        foreach (var peer in peerMessages)
        {
            switch (FomoxaCheckMessage(peer.Id, peer.FieldCount, peer.Fingerprint, out _))
            {
                case FomoxaMessageCheck.Reject:
                    // One mismatch decides the whole session. Every other message
                    // could agree and it would still be unsafe to speak.
                    return FomoxaHandshake.Reject;
                case FomoxaMessageCheck.NeedPrefix:
                    needMore = true;
                    break;
            }
        }

        return needMore ? FomoxaHandshake.NeedMore : FomoxaHandshake.Outdated;
    }

    /// <summary>Whether this schema was generated with validate_message_fingerprint.</summary>
    public const bool FomoxaValidateMessageFingerprint = false;

    // Per-frame message validation is off, so no envelope is generated and no
    // frame carries one. Turn it on in fomoxa.toml:
    //
    //     validate_message_fingerprint = true
    //
    // and every frame gains [MessageId: uint][MessageFingerprint: ulong] in front of
    // its payload, with FomoxaWriteEnvelope / FomoxaReadEnvelope to match.
}

}
