// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/InputFrames.cs
// model: InputFrames
// codec: net
// fingerprint: sha256:0ff27abfb43d4c62327a56de5389c6b43bc9fc74a24bc97c3711b8790e3bb2ce
// fomoxac-version: 0.2.2
// generated-at: 2026-10-02T04:33:47Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="InputFrames"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Tick</c>: <c>u32</c></description></item>
/// <item><description><c>Frames</c>: <c>Array&lt;bytes&gt;</c></description></item>
/// </list>
/// </remarks>
public static class InputFramesNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "InputFrames.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x5D0051BA;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x0FF27ABFB43D4C62;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.InputFrames value)
    {
        writer.WriteU32(value.Tick);
        writer.WriteArrayCount(value.Frames.Count);
        foreach (var element in value.Frames)
        {
            writer.WriteBytes(element);
        }
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.InputFrames value)
    {
        value.Tick = reader.FieldAbsent() ? 0 : reader.ReadU32();
        int framesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var framesValueList = ArrayField.Reuse(value.Frames, framesValueCount);
        for (int i = 0; i < framesValueCount; i++)
        {
            var element = i < framesValueList.Count ? framesValueList[i] : default;
            reader.ReadBytes(ref element);
            if (i < framesValueList.Count)
            {
                framesValueList[i] = element;
            }
            else
            {
                framesValueList.Add(element);
            }
        }
        ArrayField.Trim(framesValueList, framesValueCount);
        value.Frames = framesValueList;
    }
}

}
