// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/LocalPeer.cs
// model: LocalPeer
// codec: net
// fingerprint: sha256:a5d4734ef76f4dfcd539619779903f7f48d2208ba688bd33f635827c3134aa6b
// fomoxac-version: 0.2.2
// generated-at: 2026-10-02T07:40:56Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="LocalPeer"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>PeerId</c>: <c>u64</c></description></item>
/// <item><description><c>TickRate</c>: <c>u16</c></description></item>
/// <item><description><c>PhysicsBackend</c>: <c>u8</c></description></item>
/// </list>
/// </remarks>
public static class LocalPeerNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "LocalPeer.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x90528974;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0xA5D4734EF76F4DFC;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.LocalPeer value)
    {
        writer.WriteU64(value.PeerId);
        writer.WriteU16(value.TickRate);
        writer.WriteU8(value.PhysicsBackend);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.LocalPeer value)
    {
        value.PeerId = reader.FieldAbsent() ? 0 : reader.ReadU64();
        value.TickRate = reader.FieldAbsent() ? (ushort)0 : reader.ReadU16();
        value.PhysicsBackend = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
    }
}

}
