// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/MessageBundle.cs
// model: MessageBundle
// codec: net
// fingerprint: sha256:50cb0322cc54be41084fafb314ee2f3967b6d8b73cf2b231e61afbd04e5a1483
// fomoxac-version: 0.2.2
// generated-at: 2026-09-25T07:23:08Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="MessageBundle"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Entries</c>: <c>Array&lt;BundleEntry&gt;</c></description></item>
/// </list>
/// </remarks>
public static class MessageBundleNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "MessageBundle.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xA3EC30B8;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x50CB0322CC54BE41;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.MessageBundle value)
    {
        writer.WriteArrayCount(value.Entries.Count);
        foreach (var element in value.Entries)
        {
            BundleEntryNetCodec.Encode(writer, element);
        }
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.MessageBundle value)
    {
        int entriesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var entriesValueList = ArrayField.Reuse(value.Entries, entriesValueCount);
        for (int i = 0; i < entriesValueCount; i++)
        {
            var element = i < entriesValueList.Count ? entriesValueList[i] : new Fomoxa.Networking.Messaging.BundleEntry();
            BundleEntryNetCodec.Decode(ref reader, ref element);
            if (i < entriesValueList.Count)
            {
                entriesValueList[i] = element;
            }
            else
            {
                entriesValueList.Add(element);
            }
        }
        ArrayField.Trim(entriesValueList, entriesValueCount);
        value.Entries = entriesValueList;
    }
}

}
