// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/ObjectSceneSpawn.cs
// model: ObjectSceneSpawn
// codec: net
// fingerprint: sha256:a93d679db7a042d3f80204db045883b9a10ff5be55badf494a9b0dda1f84d3a5
// fomoxac-version: 0.2.2
// generated-at: 2026-10-01T08:58:14Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="ObjectSceneSpawn"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>ObjectId</c>: <c>u32</c></description></item>
/// <item><description><c>SceneObjectId</c>: <c>u64</c></description></item>
/// <item><description><c>Fingerprint</c>: <c>u32</c></description></item>
/// <item><description><c>OwnerId</c>: <c>u64</c></description></item>
/// <item><description><c>Mask</c>: <c>u8</c></description></item>
/// <item><description><c>Values</c>: <c>Array&lt;f32&gt;</c></description></item>
/// <item><description><c>States</c>: <c>Array&lt;bytes&gt;</c></description></item>
/// </list>
/// </remarks>
public static class ObjectSceneSpawnNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "ObjectSceneSpawn.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x756E5838;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0xA93D679DB7A042D3;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.ObjectSceneSpawn value)
    {
        writer.WriteU32(value.ObjectId);
        writer.WriteU64(value.SceneObjectId);
        writer.WriteU32(value.Fingerprint);
        writer.WriteU64(value.OwnerId);
        writer.WriteU8(value.Mask);
        writer.WriteArrayCount(value.Values.Count);
        foreach (var element in value.Values)
        {
            writer.WriteF32(element);
        }
        writer.WriteArrayCount(value.States.Count);
        foreach (var element in value.States)
        {
            writer.WriteBytes(element);
        }
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.ObjectSceneSpawn value)
    {
        value.ObjectId = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.SceneObjectId = reader.FieldAbsent() ? 0 : reader.ReadU64();
        value.Fingerprint = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.OwnerId = reader.FieldAbsent() ? 0 : reader.ReadU64();
        value.Mask = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
        int valuesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var valuesValueList = ArrayField.Reuse(value.Values, valuesValueCount);
        for (int i = 0; i < valuesValueCount; i++)
        {
            var element = reader.ReadF32();
            if (i < valuesValueList.Count)
            {
                valuesValueList[i] = element;
            }
            else
            {
                valuesValueList.Add(element);
            }
        }
        ArrayField.Trim(valuesValueList, valuesValueCount);
        value.Values = valuesValueList;
        int statesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var statesValueList = ArrayField.Reuse(value.States, statesValueCount);
        for (int i = 0; i < statesValueCount; i++)
        {
            var element = i < statesValueList.Count ? statesValueList[i] : default;
            reader.ReadBytes(ref element);
            if (i < statesValueList.Count)
            {
                statesValueList[i] = element;
            }
            else
            {
                statesValueList.Add(element);
            }
        }
        ArrayField.Trim(statesValueList, statesValueCount);
        value.States = statesValueList;
    }
}

}
