// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/ObjectOwnerChange.cs
// model: ObjectOwnerChange
// codec: net
// fingerprint: sha256:6969477015076f2070dcb0d332dc0aae89d969b5c577d6b142d8b026020ccdb2
// fomoxac-version: 0.2.2
// generated-at: 2026-09-29T09:11:41Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="ObjectOwnerChange"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>ObjectId</c>: <c>u32</c></description></item>
/// <item><description><c>OwnerId</c>: <c>u64</c></description></item>
/// </list>
/// </remarks>
public static class ObjectOwnerChangeNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "ObjectOwnerChange.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x22F1F1F7;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x6969477015076F20;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.ObjectOwnerChange value)
    {
        writer.WriteU32(value.ObjectId);
        writer.WriteU64(value.OwnerId);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.ObjectOwnerChange value)
    {
        value.ObjectId = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.OwnerId = reader.FieldAbsent() ? 0 : reader.ReadU64();
    }
}

}
