// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/ObjectDespawn.cs
// model: ObjectDespawn
// codec: net
// fingerprint: sha256:dda307de04ef42963af9d005df6c7c526963d968a3bd55d8fa62d9e0119732f4
// fomoxac-version: 0.2.2
// generated-at: 2026-09-29T09:11:41Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="ObjectDespawn"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>ObjectId</c>: <c>u32</c></description></item>
/// </list>
/// </remarks>
public static class ObjectDespawnNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "ObjectDespawn.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x517BFA7D;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0xDDA307DE04EF4296;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.ObjectDespawn value)
    {
        writer.WriteU32(value.ObjectId);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.ObjectDespawn value)
    {
        value.ObjectId = reader.FieldAbsent() ? 0 : reader.ReadU32();
    }
}

}
