// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/PeerLeave.cs
// model: PeerLeave
// codec: net
// fingerprint: sha256:2ac3087c85a8996638d23e01aa4bc0349c93b0d498a76b5d2a8c69ce0a1324f8
// fomoxac-version: 0.2.2
// generated-at: 2026-10-03T05:54:12Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="PeerLeave"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>This codec carries no fields: it encodes to zero bytes.</remarks>
public static class PeerLeaveNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "PeerLeave.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xC524CDA7;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x2AC3087C85A89966;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.PeerLeave value)
    {
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.PeerLeave value)
    {
    }
}

}
