// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/ReliableAck.cs
// model: ReliableAck
// codec: net
// fingerprint: sha256:2919cb926d7c0b4b18846f376bddf5fa7fa83924f45afd0b470f3d237a3b6282
// fomoxac-version: 0.2.2
// generated-at: 2026-09-25T07:23:08Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="ReliableAck"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Next</c>: <c>u16</c></description></item>
/// <item><description><c>Received</c>: <c>u32</c></description></item>
/// </list>
/// </remarks>
public static class ReliableAckNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "ReliableAck.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x5FE1C726;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x2919CB926D7C0B4B;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.ReliableAck value)
    {
        writer.WriteU16(value.Next);
        writer.WriteU32(value.Received);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.ReliableAck value)
    {
        value.Next = reader.FieldAbsent() ? (ushort)0 : reader.ReadU16();
        value.Received = reader.FieldAbsent() ? 0 : reader.ReadU32();
    }
}

}
