// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/SceneFile.cs
// model: SceneFilePose
// codec: net
// fingerprint: sha256:402f32a52f8fc3be9f23697a032122f72f48b9bf8256c2a743e73d5777aa6544
// fomoxac-version: 0.2.2
// generated-at: 2026-10-06T10:34:00Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="SceneFilePose"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>PositionX</c>: <c>f32</c></description></item>
/// <item><description><c>PositionY</c>: <c>f32</c></description></item>
/// <item><description><c>PositionZ</c>: <c>f32</c></description></item>
/// <item><description><c>RotationX</c>: <c>f32</c></description></item>
/// <item><description><c>RotationY</c>: <c>f32</c></description></item>
/// <item><description><c>RotationZ</c>: <c>f32</c></description></item>
/// <item><description><c>RotationW</c>: <c>f32</c></description></item>
/// <item><description><c>ScaleX</c>: <c>f32</c></description></item>
/// <item><description><c>ScaleY</c>: <c>f32</c></description></item>
/// <item><description><c>ScaleZ</c>: <c>f32</c></description></item>
/// </list>
/// </remarks>
public static class SceneFilePoseNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "SceneFilePose.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xA1C331C5;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x402F32A52F8FC3BE;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.SceneFilePose value)
    {
        writer.WriteF32(value.PositionX);
        writer.WriteF32(value.PositionY);
        writer.WriteF32(value.PositionZ);
        writer.WriteF32(value.RotationX);
        writer.WriteF32(value.RotationY);
        writer.WriteF32(value.RotationZ);
        writer.WriteF32(value.RotationW);
        writer.WriteF32(value.ScaleX);
        writer.WriteF32(value.ScaleY);
        writer.WriteF32(value.ScaleZ);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.SceneFilePose value)
    {
        value.PositionX = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.PositionY = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.PositionZ = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.RotationX = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.RotationY = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.RotationZ = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.RotationW = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.ScaleX = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.ScaleY = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.ScaleZ = reader.FieldAbsent() ? 0f : reader.ReadF32();
    }
}

}
