// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/SceneFile.cs
// model: SceneFile
// codec: net
// fingerprint: sha256:8ec26e99e1db814898183bbca51c6081853b476a68e1cd3a388f810010f49ed0
// fomoxac-version: 0.2.2
// generated-at: 2026-10-06T10:34:00Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="SceneFile"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>SceneId</c>: <c>u32</c></description></item>
/// <item><description><c>Objects</c>: <c>Array&lt;SceneFileObject&gt;</c></description></item>
/// </list>
/// </remarks>
public static class SceneFileNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "SceneFile.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xB4F8C111;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x8EC26E99E1DB8148;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.SceneFile value)
    {
        writer.WriteU32(value.SceneId);
        writer.WriteArrayCount(value.Objects.Count);
        foreach (var element in value.Objects)
        {
            SceneFileObjectNetCodec.Encode(writer, element);
        }
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.SceneFile value)
    {
        value.SceneId = reader.FieldAbsent() ? 0 : reader.ReadU32();
        int objectsValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var objectsValueList = ArrayField.Reuse(value.Objects, objectsValueCount);
        for (int i = 0; i < objectsValueCount; i++)
        {
            var element = i < objectsValueList.Count ? objectsValueList[i] : new Fomoxa.Networking.Messaging.SceneFileObject();
            SceneFileObjectNetCodec.Decode(ref reader, ref element);
            if (i < objectsValueList.Count)
            {
                objectsValueList[i] = element;
            }
            else
            {
                objectsValueList.Add(element);
            }
        }
        ArrayField.Trim(objectsValueList, objectsValueCount);
        value.Objects = objectsValueList;
    }
}

}
