// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/SceneFile.cs
// model: SceneFileBody
// codec: net
// fingerprint: sha256:89da94a05c0de9b08a37f5b084b835b565ca1cb7d8900efa9b1437872756ae0b
// fomoxac-version: 0.2.2
// generated-at: 2026-10-07T06:13:22Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="SceneFileBody"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Kind</c>: <c>u8</c></description></item>
/// <item><description><c>Mass</c>: <c>f32</c></description></item>
/// <item><description><c>Colliders</c>: <c>Array&lt;SceneFileCollider&gt;</c></description></item>
/// </list>
/// </remarks>
public static class SceneFileBodyNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "SceneFileBody.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x8E2999CF;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x89DA94A05C0DE9B0;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.SceneFileBody value)
    {
        writer.WriteU8(value.Kind);
        writer.WriteF32(value.Mass);
        writer.WriteArrayCount(value.Colliders.Count);
        foreach (var element in value.Colliders)
        {
            SceneFileColliderNetCodec.Encode(writer, element);
        }
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.SceneFileBody value)
    {
        value.Kind = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
        value.Mass = reader.FieldAbsent() ? 0f : reader.ReadF32();
        int collidersValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var collidersValueList = ArrayField.Reuse(value.Colliders, collidersValueCount);
        for (int i = 0; i < collidersValueCount; i++)
        {
            var element = i < collidersValueList.Count ? collidersValueList[i] : new Fomoxa.Networking.Messaging.SceneFileCollider();
            SceneFileColliderNetCodec.Decode(ref reader, ref element);
            if (i < collidersValueList.Count)
            {
                collidersValueList[i] = element;
            }
            else
            {
                collidersValueList.Add(element);
            }
        }
        ArrayField.Trim(collidersValueList, collidersValueCount);
        value.Colliders = collidersValueList;
    }
}

}
