// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/SceneFile.cs
// model: SceneFileMaterial
// codec: net
// fingerprint: sha256:18e04a1f8bc79a1691e7b8d8ef0950172e917a40debcb61ba9cdf68fc6ff69ba
// fomoxac-version: 0.2.2
// generated-at: 2026-10-07T06:13:22Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="SceneFileMaterial"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Friction</c>: <c>f32</c></description></item>
/// <item><description><c>Restitution</c>: <c>f32</c></description></item>
/// <item><description><c>FrictionCombine</c>: <c>u8</c></description></item>
/// <item><description><c>RestitutionCombine</c>: <c>u8</c></description></item>
/// </list>
/// </remarks>
public static class SceneFileMaterialNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "SceneFileMaterial.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xDF07827C;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x18E04A1F8BC79A16;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.SceneFileMaterial value)
    {
        writer.WriteF32(value.Friction);
        writer.WriteF32(value.Restitution);
        writer.WriteU8(value.FrictionCombine);
        writer.WriteU8(value.RestitutionCombine);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.SceneFileMaterial value)
    {
        value.Friction = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.Restitution = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.FrictionCombine = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
        value.RestitutionCombine = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
    }
}

}
