// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/SceneFile.cs
// model: SceneFileCollider2D
// codec: net
// fingerprint: sha256:95e8d55e703fd8b46363c7719ac85efdfca870ccafe8276ef1072962327d28ec
// fomoxac-version: 0.2.2
// generated-at: 2026-10-07T06:13:22Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="SceneFileCollider2D"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Kind</c>: <c>u8</c></description></item>
/// <item><description><c>PositionX</c>: <c>f32</c></description></item>
/// <item><description><c>PositionY</c>: <c>f32</c></description></item>
/// <item><description><c>Rotation</c>: <c>f32</c></description></item>
/// <item><description><c>HalfExtentsX</c>: <c>f32</c></description></item>
/// <item><description><c>HalfExtentsY</c>: <c>f32</c></description></item>
/// <item><description><c>Radius</c>: <c>f32</c></description></item>
/// <item><description><c>HalfHeight</c>: <c>f32</c></description></item>
/// <item><description><c>Points</c>: <c>Array&lt;f32&gt;</c></description></item>
/// <item><description><c>Material</c>: <c>SceneFileMaterial</c></description></item>
/// <item><description><c>Layer</c>: <c>u8</c></description></item>
/// <item><description><c>IsTrigger</c>: <c>bool</c></description></item>
/// </list>
/// </remarks>
public static class SceneFileCollider2DNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "SceneFileCollider2D.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x5E210AD5;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x95E8D55E703FD8B4;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.SceneFileCollider2D value)
    {
        writer.WriteU8(value.Kind);
        writer.WriteF32(value.PositionX);
        writer.WriteF32(value.PositionY);
        writer.WriteF32(value.Rotation);
        writer.WriteF32(value.HalfExtentsX);
        writer.WriteF32(value.HalfExtentsY);
        writer.WriteF32(value.Radius);
        writer.WriteF32(value.HalfHeight);
        writer.WriteArrayCount(value.Points.Count);
        foreach (var element in value.Points)
        {
            writer.WriteF32(element);
        }
        SceneFileMaterialNetCodec.Encode(writer, value.Material);
        writer.WriteU8(value.Layer);
        writer.WriteBool(value.IsTrigger);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.SceneFileCollider2D value)
    {
        value.Kind = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
        value.PositionX = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.PositionY = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.Rotation = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.HalfExtentsX = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.HalfExtentsY = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.Radius = reader.FieldAbsent() ? 0f : reader.ReadF32();
        value.HalfHeight = reader.FieldAbsent() ? 0f : reader.ReadF32();
        int pointsValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var pointsValueList = ArrayField.Reuse(value.Points, pointsValueCount);
        for (int i = 0; i < pointsValueCount; i++)
        {
            var element = reader.ReadF32();
            if (i < pointsValueList.Count)
            {
                pointsValueList[i] = element;
            }
            else
            {
                pointsValueList.Add(element);
            }
        }
        ArrayField.Trim(pointsValueList, pointsValueCount);
        value.Points = pointsValueList;
        var materialValue = value.Material;
        SceneFileMaterialNetCodec.Decode(ref reader, ref materialValue);
        value.Material = materialValue;
        value.Layer = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
        value.IsTrigger = reader.FieldAbsent() ? false : reader.ReadBool();
    }
}

}
