// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/SceneLoad.cs
// model: SceneLoad
// codec: net
// fingerprint: sha256:0061dc248bd029c7cda79bba1ca10d3a7a22d17b4209c989257d80c9ae3c60dd
// fomoxac-version: 0.2.2
// generated-at: 2026-10-01T15:31:04Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="SceneLoad"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Full</c>: <c>bool</c></description></item>
/// <item><description><c>Scenes</c>: <c>Array&lt;u32&gt;</c></description></item>
/// </list>
/// </remarks>
public static class SceneLoadNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "SceneLoad.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x4D3D43BA;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x0061DC248BD029C7;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.SceneLoad value)
    {
        writer.WriteBool(value.Full);
        writer.WriteArrayCount(value.Scenes.Count);
        foreach (var element in value.Scenes)
        {
            writer.WriteU32(element);
        }
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.SceneLoad value)
    {
        value.Full = reader.FieldAbsent() ? false : reader.ReadBool();
        int scenesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var scenesValueList = ArrayField.Reuse(value.Scenes, scenesValueCount);
        for (int i = 0; i < scenesValueCount; i++)
        {
            var element = reader.ReadU32();
            if (i < scenesValueList.Count)
            {
                scenesValueList[i] = element;
            }
            else
            {
                scenesValueList.Add(element);
            }
        }
        ArrayField.Trim(scenesValueList, scenesValueCount);
        value.Scenes = scenesValueList;
    }
}

}
