// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/SceneFile.cs
// model: SceneFileObject
// codec: net
// fingerprint: sha256:59c69ba0955be7cdc8b6dc66f25786232b64ac879a97e288690d9ec030760b8b
// fomoxac-version: 0.2.2
// generated-at: 2026-10-06T10:34:00Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="SceneFileObject"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>SceneObjectId</c>: <c>u64</c></description></item>
/// <item><description><c>Fingerprint</c>: <c>u32</c></description></item>
/// <item><description><c>BehaviourTypes</c>: <c>Array&lt;string&gt;</c></description></item>
/// <item><description><c>Pose</c>: <c>SceneFilePose</c></description></item>
/// </list>
/// </remarks>
public static class SceneFileObjectNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "SceneFileObject.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xA8BBC53D;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x59C69BA0955BE7CD;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.SceneFileObject value)
    {
        writer.WriteU64(value.SceneObjectId);
        writer.WriteU32(value.Fingerprint);
        writer.WriteArrayCount(value.BehaviourTypes.Count);
        foreach (var element in value.BehaviourTypes)
        {
            writer.WriteString(element);
        }
        SceneFilePoseNetCodec.Encode(writer, value.Pose);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.SceneFileObject value)
    {
        value.SceneObjectId = reader.FieldAbsent() ? 0 : reader.ReadU64();
        value.Fingerprint = reader.FieldAbsent() ? 0 : reader.ReadU32();
        int behaviourTypesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var behaviourTypesValueList = ArrayField.Reuse(value.BehaviourTypes, behaviourTypesValueCount);
        for (int i = 0; i < behaviourTypesValueCount; i++)
        {
            var element = i < behaviourTypesValueList.Count ? behaviourTypesValueList[i] : default;
            reader.ReadString(ref element);
            if (i < behaviourTypesValueList.Count)
            {
                behaviourTypesValueList[i] = element;
            }
            else
            {
                behaviourTypesValueList.Add(element);
            }
        }
        ArrayField.Trim(behaviourTypesValueList, behaviourTypesValueCount);
        value.BehaviourTypes = behaviourTypesValueList;
        var poseValue = value.Pose;
        SceneFilePoseNetCodec.Decode(ref reader, ref poseValue);
        value.Pose = poseValue;
    }
}

}
