// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/StateResync.cs
// model: StateResync
// codec: net
// fingerprint: sha256:036db9745ffc78fa23426f2ef3ef2280dc5cd08dbbbf8d29833d2aa7aa72f3dd
// fomoxac-version: 0.2.2
// generated-at: 2026-10-01T09:39:51Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="StateResync"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>This codec carries no fields: it encodes to zero bytes.</remarks>
public static class StateResyncNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "StateResync.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x1B21B0D1;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x036DB9745FFC78FA;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.StateResync value)
    {
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.StateResync value)
    {
    }
}

}
