// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/StateDelta.cs
// model: StateDelta
// codec: net
// fingerprint: sha256:c709753ce0caedb5e7670451807766fa1dac85f57da87f3a52dfad1227ae165c
// fomoxac-version: 0.2.2
// generated-at: 2026-10-01T09:39:51Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="StateDelta"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Data</c>: <c>bytes</c></description></item>
/// </list>
/// </remarks>
public static class StateDeltaNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "StateDelta.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xEE8A1FC0;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0xC709753CE0CAEDB5;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.StateDelta value)
    {
        writer.WriteBytes(value.Data);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.StateDelta value)
    {
        var dataValue = value.Data;
        if (reader.FieldAbsent())
        {
            dataValue = System.Array.Empty<byte>();
        }
        else
        {
            reader.ReadBytes(ref dataValue);
        }
        value.Data = dataValue;
    }
}

}
