// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/TickPong.cs
// model: TickPong
// codec: net
// fingerprint: sha256:89fef9f4fb791b95a7bd49fea7f4561222387be3f66218ad068f92f6efcf9981
// fomoxac-version: 0.2.2
// generated-at: 2026-10-02T03:58:44Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="TickPong"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>ClientTime</c>: <c>u32</c></description></item>
/// <item><description><c>ServerTick</c>: <c>u32</c></description></item>
/// <item><description><c>InputLead</c>: <c>i16</c></description></item>
/// </list>
/// </remarks>
public static class TickPongNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "TickPong.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xC9F14452;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x89FEF9F4FB791B95;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.TickPong value)
    {
        writer.WriteU32(value.ClientTime);
        writer.WriteU32(value.ServerTick);
        writer.WriteI16(value.InputLead);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.TickPong value)
    {
        value.ClientTime = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.ServerTick = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.InputLead = reader.FieldAbsent() ? (short)0 : reader.ReadI16();
    }
}

}
