// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/TickPing.cs
// model: TickPing
// codec: net
// fingerprint: sha256:1d6e28cf0d4b9ab361b7f95524b592406c50d5e9707de7a756d9ddfc70c9d02d
// fomoxac-version: 0.2.2
// generated-at: 2026-10-02T03:58:44Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="TickPing"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>ClientTime</c>: <c>u32</c></description></item>
/// <item><description><c>Rtt</c>: <c>u16</c></description></item>
/// </list>
/// </remarks>
public static class TickPingNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "TickPing.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0xC19D0BA9;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x1D6E28CF0D4B9AB3;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.TickPing value)
    {
        writer.WriteU32(value.ClientTime);
        writer.WriteU16(value.Rtt);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.TickPing value)
    {
        value.ClientTime = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.Rtt = reader.FieldAbsent() ? (ushort)0 : reader.ReadU16();
    }
}

}
