// GENERATED BY fomoxac
// DO NOT EDIT MANUALLY
// source: Runtime/Core/SystemModels/TransformSettle.cs
// model: TransformSettle
// codec: net
// fingerprint: sha256:671368cb7bbe68d822b56311a3ed8cc74db12fcf9406f2798f6ad42f092f28f5
// fomoxac-version: 0.2.2
// generated-at: 2026-10-03T03:25:11Z

namespace BundleFixture
{

/// <summary>The <c>net</c> codec for <see cref="TransformSettle"/>, generated from its Fomoxa attributes.</summary>
/// <remarks>
/// The wire layout, in declaration order (RFC-0002 §5.1):
/// <list type="number">
/// <item><description><c>Tick</c>: <c>u32</c></description></item>
/// <item><description><c>Mask</c>: <c>u8</c></description></item>
/// <item><description><c>Values</c>: <c>Array&lt;f32&gt;</c></description></item>
/// <item><description><c>Generation</c>: <c>u8</c></description></item>
/// </list>
/// </remarks>
public static class TransformSettleNetCodec
{
    /// <summary>This message's name: <c>Model.codec</c>.</summary>
    public const string MessageName = "TransformSettle.net";

    /// <summary>This message's stable id, derived from its name alone.</summary>
    public const uint MessageId = 0x62ADC0F1;

    /// <summary>This message's wire-contract fingerprint - the same value
    /// <c>Handshake.cs</c> publishes, and the one a peer compares against.</summary>
    public const ulong Fingerprint = 0x671368CB7BBE68D8;

    /// <summary>Writes the <c>net</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Fomoxa.Networking.Messaging.TransformSettle value)
    {
        writer.WriteU32(value.Tick);
        writer.WriteU8(value.Mask);
        writer.WriteArrayCount(value.Values.Count);
        foreach (var element in value.Values)
        {
            writer.WriteF32(element);
        }
        writer.WriteU8(value.Generation);
    }

    /// <summary>Reads the <c>net</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>
    /// Fields this codec does not carry are left as they were, which is what lets one
    /// model be split across several codecs.
    ///
    /// A field the stream ended before takes its zero value (RFC-0002 §9.1); a field
    /// the stream ended inside is an error. Bytes left over after the last field
    /// belong to a newer writer's model and are ignored.
    /// </remarks>
    public static void Decode(ref Reader reader, ref Fomoxa.Networking.Messaging.TransformSettle value)
    {
        value.Tick = reader.FieldAbsent() ? 0 : reader.ReadU32();
        value.Mask = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
        int valuesValueCount = reader.FieldAbsent() ? 0 : reader.ReadArrayCount();
        var valuesValueList = ArrayField.Reuse(value.Values, valuesValueCount);
        for (int i = 0; i < valuesValueCount; i++)
        {
            var element = reader.ReadF32();
            if (i < valuesValueList.Count)
            {
                valuesValueList[i] = element;
            }
            else
            {
                valuesValueList.Add(element);
            }
        }
        ArrayField.Trim(valuesValueList, valuesValueCount);
        value.Values = valuesValueList;
        value.Generation = reader.FieldAbsent() ? (byte)0 : reader.ReadU8();
    }
}

}
