using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Fomoxa.Networking;

namespace Fomoxa.Unity.Editor
{
    public readonly struct FomoxaGenerateResult
    {
        private FomoxaGenerateResult(bool succeeded, bool changed, string error, string warnings)
        {
            Succeeded = succeeded;
            Changed = changed;
            Error = error;
            Warnings = warnings;
        }

        public bool Succeeded { get; }

        public bool Changed { get; }

        public string Error { get; }

        public string Warnings { get; }

        public static FomoxaGenerateResult Success(bool changed, string warnings) =>
            new FomoxaGenerateResult(true, changed, null, warnings);

        public static FomoxaGenerateResult Failure(string error) =>
            new FomoxaGenerateResult(false, false, error, null);
    }

    public static class FomoxaGenerator
    {
        public const string TomlFileName = "fomoxa.toml";
        public const string TomlMarker = "# Generated by com.fomoxa.networking from the FomoxaSettings asset. Edit the asset, not this file.";
        public const string NetSchemaFileName = "NetSchema.cs";
        public const string AdaptersFileName = "FomoxaAdapters.cs";
        public const string RegistrationFileName = "FomoxaUnityRegistration.cs";
        public const string SystemModelsFolder = "FomoxaSystemModels";
        public const string SystemModelMarker = "// Copied by com.fomoxa.networking from its system models. Edit the package, not this file.";
        public const string AdapterMarker = "// Generated by com.fomoxa.networking from a fomoxac codec. Edit the model, not this file.";
        public const string RpcModelsFolder = "RpcModels";
        public const string RpcModelsNamespace = "FomoxaRpcModels";
        public const string RpcModelMarker = "// Generated by com.fomoxa.networking from [NetworkRpc] ";
        public const string KeepFileName = ".gitkeep";

        public const string SystemCodec = "net";

        public static readonly IReadOnlyList<string> SystemAdapterModels = new[]
        {
            "MessageBundle",
            "ReliableAck",
            "LocalPeer",
            "ObjectSpawn",
            "ObjectSceneSpawn",
            "ObjectDespawn",
            "ObjectOwnerChange",
            "StateDelta",
            "StateResync",
            "TransformUpdate",
            "TransformSettle",
            "AnimatorState",
            "SceneLoad",
            "SceneUnload",
            "SceneLoaded",
            "TickPing",
            "TickPong",
            "InputFrames",
            "ReconcileState",
            "PeerLeave",
            "SceneFile",
        };

        private static readonly Regex ModelLine = new Regex(@"^// model: (\S+)\r?$", RegexOptions.Multiline);
        private static readonly Regex CodecLine = new Regex(@"^// codec: (\S+)\r?$", RegexOptions.Multiline);
        private static readonly Regex CodecClassLine = new Regex(@"^public static class ([A-Za-z_][A-Za-z0-9_]*)\r?$", RegexOptions.Multiline);
        private static readonly Regex EncodeLine = new Regex(@"^\s*public static void Encode\(Writer writer, ([A-Za-z_][A-Za-z0-9_.]*) value\)\r?$", RegexOptions.Multiline);
        private static readonly Regex NamespaceLine = new Regex(@"^\s*namespace\s+([A-Za-z_][A-Za-z0-9_.]*)", RegexOptions.Multiline);
        private static readonly UTF8Encoding Utf8WithoutBom = new UTF8Encoding(false);

        public static FomoxaGenerateResult Run(
            string projectRoot,
            string modelsFolder,
            string generatedFolder,
            string fomoxacPath,
            string systemModelsSource,
            IReadOnlyList<ChannelDeclaration> channels,
            IReadOnlyList<RpcDeclaration> rpcs)
        {
            if (channels == null)
            {
                throw new ArgumentNullException(nameof(channels));
            }

            if (rpcs == null)
            {
                throw new ArgumentNullException(nameof(rpcs));
            }

            if (string.IsNullOrWhiteSpace(modelsFolder) || string.IsNullOrWhiteSpace(generatedFolder))
            {
                return FomoxaGenerateResult.Failure("the FomoxaSettings asset needs both a models folder and a generated folder");
            }

            if (fomoxacPath == null || !File.Exists(fomoxacPath))
            {
                return FomoxaGenerateResult.Failure($"the fomoxac binary for this editor platform is missing: {fomoxacPath ?? "unsupported platform"}");
            }

            string tomlPath = Path.Combine(projectRoot, TomlFileName);
            if (File.Exists(tomlPath) && !File.ReadAllText(tomlPath).StartsWith(TomlMarker))
            {
                return FomoxaGenerateResult.Failure($"{tomlPath} was not written by com.fomoxa.networking; remove it and set its paths in the FomoxaSettings asset");
            }

            if (systemModelsSource == null || !Directory.Exists(systemModelsSource))
            {
                return FomoxaGenerateResult.Failure($"the system models of com.fomoxa.networking are missing: {systemModelsSource ?? "package not found"}");
            }

            if (!CopySystemModels(systemModelsSource, Path.Combine(projectRoot, SystemModelsFolder), out bool changed, out string copyError))
            {
                return FomoxaGenerateResult.Failure(copyError);
            }

            if (!WriteRpcModels(Path.Combine(projectRoot, generatedFolder, RpcModelsFolder), rpcs, out bool rpcModelsChanged, out string rpcError))
            {
                return FomoxaGenerateResult.Failure(rpcError);
            }

            changed |= rpcModelsChanged;
            changed |= WriteIfChanged(tomlPath, Toml(modelsFolder, generatedFolder));

            if (!RunFomoxac(fomoxacPath, projectRoot, out string warnings, out string error))
            {
                return FomoxaGenerateResult.Failure(error);
            }

            string outputFolder = Path.Combine(projectRoot, generatedFolder);
            string namespaceName = NamespaceOf(outputFolder);
            if (namespaceName == null)
            {
                return FomoxaGenerateResult.Failure($"fomoxac did not write a namespaced {Path.Combine(outputFolder, NetSchemaFileName)}");
            }

            if (!FomoxaUnityCodecs.Write(projectRoot, outputFolder, namespaceName, out bool unityCodecsChanged, out string unityWarnings, out string unityError))
            {
                return FomoxaGenerateResult.Failure(unityError);
            }

            changed |= unityCodecsChanged;
            warnings = unityWarnings == null ? warnings : warnings == null ? unityWarnings : warnings + "\n" + unityWarnings;

            Dictionary<string, GeneratedCodec> codecs = GeneratedCodecs(outputFolder);
            IEnumerable<string> needed = SystemAdapterModels.Select(model => model + "." + SystemCodec)
                .Concat(channels.Select(channel => channel.Model + "." + channel.Codec))
                .Concat(rpcs.Select(rpc => rpc.Model + "." + SystemCodec));
            string missing = needed.FirstOrDefault(message => !codecs.ContainsKey(message));
            if (missing != null)
            {
                return FomoxaGenerateResult.Failure($"fomoxac did not generate a codec for {missing} in {outputFolder}");
            }

            var adapterFiles = new HashSet<string>(StringComparer.Ordinal);
            foreach (GeneratedCodec codec in codecs.Values.OrderBy(codec => codec.ClassName, StringComparer.Ordinal))
            {
                string adapterFile = AdapterName(codec.ClassName) + ".cs";
                adapterFiles.Add(adapterFile);
                changed |= WriteIfChanged(Path.Combine(outputFolder, adapterFile), Adapter(namespaceName, codec));
            }

            changed |= RemoveStaleAdapters(outputFolder, adapterFiles);

            changed |= WriteIfChanged(Path.Combine(outputFolder, AdaptersFileName), Adapters(namespaceName, channels, rpcs, codecs));
            changed |= WriteIfChanged(Path.Combine(outputFolder, RegistrationFileName), Registration(namespaceName));
            return FomoxaGenerateResult.Success(changed, warnings);
        }

        public static IReadOnlyList<string> CheckRpcs(string projectRoot, string generatedFolder, IReadOnlyList<RpcDeclaration> rpcs)
        {
            string outputFolder = Path.Combine(projectRoot, generatedFolder);
            string adaptersPath = Path.Combine(outputFolder, AdaptersFileName);
            string adapters = File.Exists(adaptersPath) ? File.ReadAllText(adaptersPath).Replace("\r\n", "\n") : "";
            Dictionary<string, GeneratedCodec> codecs = Directory.Exists(outputFolder) ? GeneratedCodecs(outputFolder) : new Dictionary<string, GeneratedCodec>();
            var errors = new List<string>();
            foreach (RpcDeclaration rpc in rpcs)
            {
                string where = $"[NetworkRpc] {rpc.Type}.{rpc.Method}";
                string modelPath = Path.Combine(outputFolder, RpcModelsFolder, rpc.Model + ".cs");
                if (!File.Exists(modelPath) || File.ReadAllText(modelPath).Replace("\r\n", "\n") != RpcModel(rpc))
                {
                    errors.Add($"{where}: its model {rpc.Model} in {Path.Combine(generatedFolder, RpcModelsFolder)} is missing or out of date");
                }
                else if (!codecs.TryGetValue(rpc.Model + "." + SystemCodec, out GeneratedCodec codec))
                {
                    errors.Add($"{where}: fomoxac has not generated a codec for {rpc.Model}.{SystemCodec}");
                }
                else if (!adapters.Contains(RpcRegistration(rpc, codec)))
                {
                    errors.Add($"{where}: {AdaptersFileName} does not register it");
                }
            }

            if (errors.Count > 0)
            {
                errors.Add("run Tools > Fomoxa > Generate and commit the generated files");
            }

            return errors;
        }

        public static string RpcModel(RpcDeclaration rpc) =>
            RpcModelMarker + $"{rpc.Type}.{rpc.Method}. Edit the method, not this file.\n"
            + "using Fomoxa;\n"
            + "using Fomoxa.Networking;\n"
            + "\n"
            + $"namespace {RpcModelsNamespace}\n"
            + "{\n"
            + "    [Network]\n"
            + $"    [Codec(\"{SystemCodec}\")]\n"
            + $"    [NetworkChannel(\"{SystemCodec}\", Channel.{rpc.Channel})]\n"
            + $"    public sealed class {rpc.Model}\n"
            + "    {\n"
            + "    }\n"
            + "}\n";

        public static string NamespaceOf(string outputFolder)
        {
            string netSchemaPath = Path.Combine(outputFolder, NetSchemaFileName);
            Match namespaceMatch = File.Exists(netSchemaPath) ? NamespaceLine.Match(File.ReadAllText(netSchemaPath)) : Match.Empty;
            return namespaceMatch.Success ? namespaceMatch.Groups[1].Value : null;
        }

        private static bool RunFomoxac(string fomoxacPath, string projectRoot, out string warnings, out string error)
        {
            var start = new ProcessStartInfo(fomoxacPath, "generate -q")
            {
                WorkingDirectory = projectRoot,
                UseShellExecute = false,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                CreateNoWindow = true,
            };

            using (Process process = Process.Start(start))
            {
                Task<string> standardError = process.StandardError.ReadToEndAsync();
                string standardOutput = process.StandardOutput.ReadToEnd();
                process.WaitForExit();
                string messages = (standardOutput + standardError.Result).Trim();
                if (process.ExitCode != 0)
                {
                    warnings = null;
                    error = $"fomoxac generate exited with {process.ExitCode}: {messages}";
                    return false;
                }

                warnings = messages.Length == 0 ? null : messages;
                error = null;
                return true;
            }
        }

        private static string Toml(string modelsFolder, string generatedFolder) =>
            TomlMarker + "\n"
            + $"src = [{TomlString(modelsFolder)}, {TomlString(SystemModelsFolder)}, {TomlString(generatedFolder.TrimEnd('/', '\\') + "/" + RpcModelsFolder)}]\n"
            + $"out = {TomlString(generatedFolder)}\n"
            + "net_schema = true\n";

        private static string TomlString(string path) =>
            "\"" + path.Trim().Replace('\\', '/').Replace("\"", "\\\"") + "\"";

        private static string Adapters(string namespaceName, IReadOnlyList<ChannelDeclaration> channels, IReadOnlyList<RpcDeclaration> rpcs, Dictionary<string, GeneratedCodec> codecs)
        {
            var text = new StringBuilder()
                .Append($"namespace {namespaceName}\n")
                .Append("{\n")
                .Append("    public static class FomoxaAdapters\n")
                .Append("    {\n")
                .Append("        public static void RegisterAll(global::Fomoxa.Networking.FomoxaRegistry registry)\n")
                .Append("        {\n")
                .Append("            registry.SetSchema(NetSchema.Build());\n");
            foreach (string model in SystemAdapterModels)
            {
                text.Append($"            registry.SetCodec({model}NetAdapter.Instance);\n");
            }

            foreach (ChannelDeclaration channel in channels)
            {
                text.Append($"            registry.Channels.Set({codecs[channel.Model + "." + channel.Codec].ClassName}.MessageId, global::Fomoxa.Networking.Channel.{channel.Channel});\n");
            }

            foreach (RpcDeclaration rpc in rpcs)
            {
                GeneratedCodec codec = codecs[rpc.Model + "." + SystemCodec];
                if (rpc.Channel != Channel.Unreliable)
                {
                    text.Append($"            registry.Channels.Set({codec.ClassName}.MessageId, global::Fomoxa.Networking.Channel.{rpc.Channel});\n");
                }

                text.Append(RpcRegistration(rpc, codec));
            }

            return text
                .Append("        }\n")
                .Append("    }\n")
                .Append("}\n")
                .ToString();
        }

        private static string RpcRegistration(RpcDeclaration rpc, GeneratedCodec codec) =>
            $"            registry.Rpcs.Set(\"{rpc.Type}\", \"{rpc.Method}\", {codec.ClassName}.MessageId);\n";

        private static bool WriteRpcModels(string folder, IReadOnlyList<RpcDeclaration> rpcs, out bool changed, out string error)
        {
            changed = WriteIfChanged(Path.Combine(folder, KeepFileName), "");
            var expected = new HashSet<string>(StringComparer.Ordinal);
            foreach (RpcDeclaration rpc in rpcs)
            {
                string file = rpc.Model + ".cs";
                string path = Path.Combine(folder, file);
                expected.Add(file);
                if (File.Exists(path) && !File.ReadAllText(path).StartsWith(RpcModelMarker))
                {
                    error = $"{path} was not written by com.fomoxa.networking; remove it or give [NetworkRpc] {rpc.Type}.{rpc.Method} another model name";
                    return false;
                }

                changed |= WriteIfChanged(path, RpcModel(rpc));
            }

            foreach (string stale in Directory.GetFiles(folder, "*.cs"))
            {
                if (!expected.Contains(Path.GetFileName(stale)) && File.ReadAllText(stale).StartsWith(RpcModelMarker))
                {
                    File.Delete(stale);
                    changed = true;
                }
            }

            error = null;
            return true;
        }

        public static string AdapterName(string codecClass) =>
            (codecClass.EndsWith("Codec", StringComparison.Ordinal) ? codecClass.Substring(0, codecClass.Length - "Codec".Length) : codecClass) + "Adapter";

        private static string Adapter(string namespaceName, GeneratedCodec codec)
        {
            string adapter = AdapterName(codec.ClassName);
            string model = "global::" + codec.ModelType;
            return AdapterMarker + "\n"
                + $"namespace {namespaceName}\n"
                + "{\n"
                + $"    [global::Fomoxa.Networking.MessageAdapter(\"{codec.Codec}\")]\n"
                + $"    public sealed class {adapter} : global::Fomoxa.Networking.Messaging.IMessageCodec<{model}>\n"
                + "    {\n"
                + $"        public static readonly {adapter} Instance = new {adapter}();\n"
                + "\n"
                + "        private readonly Writer writer = new Writer();\n"
                + "\n"
                + $"        public uint MessageId => {codec.ClassName}.MessageId;\n"
                + "\n"
                + $"        public global::System.ReadOnlyMemory<byte> Encode({model} value)\n"
                + "        {\n"
                + "            writer.Clear();\n"
                + $"            {codec.ClassName}.Encode(writer, value);\n"
                + "            return writer.WrittenMemory;\n"
                + "        }\n"
                + "\n"
                + $"        public void Decode(global::System.ReadOnlyMemory<byte> payload, ref {model} value)\n"
                + "        {\n"
                + "            var reader = new Reader(payload);\n"
                + "            try\n"
                + "            {\n"
                + $"                {codec.ClassName}.Decode(ref reader, ref value);\n"
                + "            }\n"
                + "            catch (DecodeException error)\n"
                + "            {\n"
                + "                throw new global::Fomoxa.Networking.Messaging.MessageDecodeException(error.Message, error);\n"
                + "            }\n"
                + "        }\n"
                + "    }\n"
                + "}\n";
        }

        private static bool RemoveStaleAdapters(string outputFolder, HashSet<string> adapterFiles)
        {
            bool removed = false;
            foreach (string file in Directory.GetFiles(outputFolder, "*.cs"))
            {
                if (!adapterFiles.Contains(Path.GetFileName(file)) && File.ReadAllText(file).StartsWith(AdapterMarker))
                {
                    File.Delete(file);
                    removed = true;
                }
            }

            return removed;
        }

        private static Dictionary<string, GeneratedCodec> GeneratedCodecs(string outputFolder)
        {
            var codecs = new Dictionary<string, GeneratedCodec>(StringComparer.Ordinal);
            foreach (string file in Directory.GetFiles(outputFolder, "*.cs"))
            {
                string text = File.ReadAllText(file);
                Match model = ModelLine.Match(text);
                Match codec = CodecLine.Match(text);
                Match codecClass = CodecClassLine.Match(text);
                Match encode = EncodeLine.Match(text);
                if (model.Success && codec.Success && codecClass.Success && encode.Success)
                {
                    codecs[model.Groups[1].Value + "." + codec.Groups[1].Value] = new GeneratedCodec(codecClass.Groups[1].Value, encode.Groups[1].Value, codec.Groups[1].Value);
                }
            }

            return codecs;
        }

        private static bool CopySystemModels(string sourceFolder, string targetFolder, out bool changed, out string error)
        {
            changed = false;
            string[] sources = Directory.GetFiles(sourceFolder, "*.cs");
            var expected = new HashSet<string>();
            foreach (string source in sources)
            {
                string target = Path.Combine(targetFolder, Path.GetFileName(source));
                expected.Add(Path.GetFileName(source));
                if (File.Exists(target) && !File.ReadAllText(target).StartsWith(SystemModelMarker))
                {
                    error = $"{target} was not written by com.fomoxa.networking; remove it so the package can copy its system models there";
                    return false;
                }

                changed |= WriteIfChanged(target, SystemModelMarker + "\n" + File.ReadAllText(source).Replace("\r\n", "\n"));
            }

            if (Directory.Exists(targetFolder))
            {
                foreach (string stale in Directory.GetFiles(targetFolder, "*.cs"))
                {
                    if (!expected.Contains(Path.GetFileName(stale)) && File.ReadAllText(stale).StartsWith(SystemModelMarker))
                    {
                        File.Delete(stale);
                        changed = true;
                    }
                }
            }

            error = null;
            return true;
        }

        private static string Registration(string namespaceName) =>
            "#if UNITY_5_3_OR_NEWER\n"
            + $"namespace {namespaceName}\n"
            + "{\n"
            + "    internal static class FomoxaUnityRegistration\n"
            + "    {\n"
            + "        [global::UnityEngine.RuntimeInitializeOnLoadMethod(global::UnityEngine.RuntimeInitializeLoadType.SubsystemRegistration)]\n"
            + "        private static void Register()\n"
            + "        {\n"
            + "            FomoxaAdapters.RegisterAll(global::Fomoxa.Networking.FomoxaRegistry.Default);\n"
            + "        }\n"
            + "    }\n"
            + "}\n"
            + "#endif\n";

        internal static bool WriteIfChanged(string path, string content)
        {
            if (File.Exists(path) && File.ReadAllText(path) == content)
            {
                return false;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content, Utf8WithoutBom);
            return true;
        }
    }

    internal readonly struct GeneratedCodec
    {
        public GeneratedCodec(string className, string modelType, string codec)
        {
            ClassName = className;
            ModelType = modelType;
            Codec = codec;
        }

        public string ClassName { get; }

        public string ModelType { get; }

        public string Codec { get; }
    }
}
