using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace Fomoxa.Unity.Editor
{
    internal static class FomoxaUnityCodecs
    {
        public const string Folder = "UnityCodecs";
        public const string Marker = "// Generated by com.fomoxa.networking for a Unity type. Edit the model, not this file.";
        public const string SchemaPath = ".fomoxa/schema.json";
        public const string InspectSchemaPath = ".fomoxa/schema.inspect.json";
        public const string InspectSource = "com.fomoxa.networking (Unity type, for fomoxa-inspect only)";

        private static readonly HashSet<string> Primitives = new HashSet<string>(StringComparer.Ordinal)
        {
            "bool", "i8", "u8", "i16", "u16", "i32", "u32", "i64", "u64", "f32", "f64", "string", "bytes",
        };

        public static bool Write(string projectRoot, string outputFolder, string namespaceName, out bool changed, out string warnings, out string error)
        {
            changed = false;
            warnings = null;
            string schemaPath = Path.Combine(projectRoot, SchemaPath);
            Dictionary<string, object> schema;
            Dictionary<string, object> models;
            try
            {
                schema = FomoxaJson.AsObject(FomoxaJson.Parse(File.ReadAllText(schemaPath)));
                models = FomoxaJson.AsObject(schema.TryGetValue("models", out object found) ? found : null);
            }
            catch (Exception exception) when (exception is IOException || exception is UnauthorizedAccessException || exception is FormatException)
            {
                error = $"cannot read {schemaPath}: {exception.Message}";
                return false;
            }

            SortedDictionary<string, SortedSet<string>> used = UnityTypeCodecs(models, out List<string> unknown, out List<string> arrays);
            string folder = Path.Combine(outputFolder, Folder);
            var expected = new HashSet<string>(StringComparer.Ordinal);
            foreach (KeyValuePair<string, SortedSet<string>> type in used)
            {
                FomoxaUnityTypes.TryGet(type.Key, out FomoxaUnityType layout);
                foreach (string codec in type.Value)
                {
                    string file = CodecClass(type.Key, codec) + ".cs";
                    string path = Path.Combine(folder, file);
                    if (File.Exists(path) && !File.ReadAllText(path).StartsWith(Marker))
                    {
                        error = $"{path} was not written by com.fomoxa.networking; remove it so the package can write the codec of the Unity type {type.Key} there";
                        return false;
                    }

                    expected.Add(file);
                    changed |= FomoxaGenerator.WriteIfChanged(path, Codec(namespaceName, type.Key, codec, layout));
                }
            }

            if (Directory.Exists(folder))
            {
                foreach (string stale in Directory.GetFiles(folder, "*.cs"))
                {
                    if (!expected.Contains(Path.GetFileName(stale)) && File.ReadAllText(stale).StartsWith(Marker))
                    {
                        File.Delete(stale);
                        changed = true;
                    }
                }
            }

            WriteInspectSchema(Path.Combine(projectRoot, InspectSchemaPath), schema, models, used);
            string joined = string.Join("\n", unknown
                .Select(field => $"the field type {field} is neither a model nor a Unity type com.fomoxa.networking knows; write its codec by hand or register it with FomoxaUnityTypes.Register")
                .Concat(arrays.Select(field => $"the field type {field} is an array of a Unity type; fomoxac writes the element type without its namespace, so the generated code does not compile; send the elements as separate fields or as a model")));
            warnings = joined.Length == 0 ? null : joined;

            error = null;
            return true;
        }

        public static string CodecClass(string typeName, string codec) => typeName + PascalCase(codec) + "Codec";

        public static string PascalCase(string identifier)
        {
            var result = new StringBuilder(identifier.Length);
            bool capitalise = true;
            foreach (char character in identifier)
            {
                if (character == '_')
                {
                    capitalise = true;
                    continue;
                }

                result.Append(capitalise ? char.ToUpperInvariant(character) : character);
                capitalise = false;
            }

            return result.ToString();
        }

        private static SortedDictionary<string, SortedSet<string>> UnityTypeCodecs(Dictionary<string, object> models, out List<string> unknown, out List<string> arrays)
        {
            var used = new SortedDictionary<string, SortedSet<string>>(StringComparer.Ordinal);
            var unknownTypes = new SortedSet<string>(StringComparer.Ordinal);
            var arrayTypes = new SortedSet<string>(StringComparer.Ordinal);
            foreach (object modelValue in models.Values)
            {
                Dictionary<string, object> model = FomoxaJson.AsObject(modelValue);
                Dictionary<string, object> messages = FomoxaJson.AsObject(model["messages"]);
                foreach (KeyValuePair<string, object> message in messages)
                {
                    foreach (object fieldValue in FomoxaJson.AsArray(FomoxaJson.AsObject(message.Value)["fields"]))
                    {
                        string spelling = FomoxaJson.AsString(FomoxaJson.AsObject(fieldValue)["type"]);
                        string leaf = LeafType(spelling);
                        if (Primitives.Contains(leaf) || models.ContainsKey(leaf))
                        {
                            continue;
                        }

                        if (!FomoxaUnityTypes.TryGet(leaf, out _))
                        {
                            unknownTypes.Add($"{leaf} (codec {message.Key})");
                            continue;
                        }

                        if (spelling != leaf)
                        {
                            arrayTypes.Add($"{spelling} (codec {message.Key})");
                        }

                        if (!used.TryGetValue(leaf, out SortedSet<string> codecs))
                        {
                            codecs = new SortedSet<string>(StringComparer.Ordinal);
                            used.Add(leaf, codecs);
                        }

                        codecs.Add(message.Key);
                    }
                }
            }

            unknown = unknownTypes.ToList();
            arrays = arrayTypes.ToList();
            return used;
        }

        private static string LeafType(string spelling)
        {
            while (spelling.StartsWith("Array<", StringComparison.Ordinal) && spelling.EndsWith(">", StringComparison.Ordinal))
            {
                spelling = spelling.Substring("Array<".Length, spelling.Length - "Array<".Length - 1);
            }

            return spelling;
        }

        private static string Codec(string namespaceName, string typeName, string codec, FomoxaUnityType layout)
        {
            var text = new StringBuilder()
                .Append(Marker).Append('\n')
                .Append($"namespace {namespaceName}\n")
                .Append("{\n")
                .Append($"    public static class {CodecClass(typeName, codec)}\n")
                .Append("    {\n")
                .Append($"        public static void Encode(Writer writer, global::{layout.FullTypeName} value)\n")
                .Append("        {\n");
            foreach (FomoxaUnityField field in layout.Fields)
            {
                text.Append($"            writer.Write{Method(field.WireType)}(value.{field.Name});\n");
            }

            text.Append("        }\n")
                .Append("\n")
                .Append($"        public static void Decode(ref Reader reader, ref global::{layout.FullTypeName} value)\n")
                .Append("        {\n");
            foreach (FomoxaUnityField field in layout.Fields)
            {
                text.Append($"            value.{field.Name} = reader.FieldAbsent() ? {Zero(field.WireType)} : reader.Read{Method(field.WireType)}();\n");
            }

            return text.Append("        }\n")
                .Append("    }\n")
                .Append("}\n")
                .ToString();
        }

        private static string Method(string wireType) => char.ToUpperInvariant(wireType[0]) + wireType.Substring(1);

        private static string Zero(string wireType)
        {
            switch (wireType)
            {
                case "bool":
                    return "false";
                case "f32":
                    return "0f";
                case "f64":
                    return "0d";
                case "i8":
                    return "(sbyte)0";
                case "u8":
                    return "(byte)0";
                case "i16":
                    return "(short)0";
                case "u16":
                    return "(ushort)0";
                case "u32":
                    return "0u";
                case "i64":
                    return "0L";
                case "u64":
                    return "0UL";
                default:
                    return "0";
            }
        }

        private static void WriteInspectSchema(string path, Dictionary<string, object> schema, Dictionary<string, object> models, SortedDictionary<string, SortedSet<string>> used)
        {
            if (used.Count == 0)
            {
                if (File.Exists(path) && File.ReadAllText(path).Contains(InspectSource))
                {
                    File.Delete(path);
                }

                return;
            }

            foreach (KeyValuePair<string, SortedSet<string>> type in used)
            {
                FomoxaUnityTypes.TryGet(type.Key, out FomoxaUnityType layout);
                var codecs = type.Value.Cast<object>().ToList();
                var modelFields = new List<object>();
                var messageFields = new List<object>();
                foreach (FomoxaUnityField field in layout.Fields)
                {
                    modelFields.Add(Object(("name", field.Name), ("type", field.WireType), ("codecs", new List<object>(codecs))));
                    messageFields.Add(Object(("name", field.Name), ("type", field.WireType)));
                }

                var messages = new Dictionary<string, object>(StringComparer.Ordinal);
                foreach (string codec in type.Value)
                {
                    messages[codec] = Object(
                        ("fingerprint", PlaceholderFingerprint($"model:{type.Key}.{codec}")),
                        ("prefixes", new List<object>()),
                        ("fields", messageFields));
                }

                models[type.Key] = Object(
                    ("source", InspectSource),
                    ("fingerprint", PlaceholderFingerprint($"model:{type.Key}")),
                    ("codecs", codecs),
                    ("fields", modelFields),
                    ("messages", messages));
            }

            FomoxaGenerator.WriteIfChanged(path, FomoxaJson.Write(schema));
        }

        private static Dictionary<string, object> Object(params (string Key, object Value)[] members)
        {
            var result = new Dictionary<string, object>(StringComparer.Ordinal);
            foreach ((string key, object value) in members)
            {
                result[key] = value;
            }

            return result;
        }

        private static string PlaceholderFingerprint(string label)
        {
            using (SHA256 sha256 = SHA256.Create())
            {
                byte[] hash = sha256.ComputeHash(Encoding.UTF8.GetBytes("com.fomoxa.networking placeholder fingerprint\n" + label));
                return "sha256:" + string.Concat(hash.Select(value => value.ToString("x2", CultureInfo.InvariantCulture)));
            }
        }
    }
}
